const Types = {
  ADD_BUDGET: 'ADD_BUDGET',
  HANDLE_MODAL_FORM: 'HANDLE_MODAL_FORM',
  HANDLE_MODAL_OPTIONS: 'HANDLE_MODAL_OPTIONS',
  TOTAL_SPENSED: 'TOTAL_SPENSED',
  AMOUNT_AVAILABLE: 'AMOUNT_AVAILABLE',
};

export default Types;
