const Types = {
  ADD_BUDGET: 'ADD_BUDGET',
  HANDLE_MODAL_FORM: 'HANDLE_MODAL_FORM',
  HANDLE_MODAL_OPTIONS: 'HANDLE_MODAL_OPTIONS',
  ADD_EXPENSES: 'ADD_EXPENSES',
  TOTAL_SPENSED: 'TOTAL_SPENSED',
  AMOUNT_AVAILABLE: 'AMOUNT_AVAILABLE',
  EDIT_EXPENSE: 'EDIT_EXPENSE',
  DELETE_EDIT_EXPENSE: 'DELETE_EDIT_EXPENSE',
  UPDATE_EXPENSE: 'UPDATE_EXPENSE',
};

export default Types;
