const Types = {
  DELETE_EDIT_EXPENSE: 'DELETE_EDIT_EXPENSE',
  PERCENTAGE_SPENSED: 'PERCENTAGE_SPENSED',
  AMOUNT_AVAILABLE: 'AMOUNT_AVAILABLE',
  CLEAN_EXPENSES: 'CLEAN_EXPENSES',
  UPDATE_EXPENSE: 'UPDATE_EXPENSE',
  DELETE_EXPENSE: 'DELETE_EXPENSE',
  TOTAL_SPENSED: 'TOTAL_SPENSED',
  ADD_EXPENSES: 'ADD_EXPENSES',
  EDIT_EXPENSE: 'EDIT_EXPENSE',
  FILTER: 'FILTER',
};

export default Types;
